" Vim color file - 
" Generated by http://bytefluent.com/vivify 2018-07-02
set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = ""

"hi  -- no settings --
